# Modified for XRVLC by XRVLC contributors on 2026-08-16.
android.enableJetifier=false
android.useAndroidX=true
kapt.incremental.apt=true
kapt.use.worker.api=true
kapt.include.compile.classpath=false
org.gradle.jvmargs=-Xms512M -Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true

POM_URL=https://github.com/ijkm1234/vlc_android_for_xr_vlc
POM_SCM_URL=https://github.com/ijkm1234/vlc_android_for_xr_vlc
POM_SCM_CONNECTION=scm:git:https://github.com/ijkm1234/vlc_android_for_xr_vlc.git
POM_SCM_DEV_CONNECTION=scm:git:https://github.com/ijkm1234/vlc_android_for_xr_vlc.git

POM_LICENCE_NAME=GNU General Public License, version 2 or later
POM_LICENCE_URL=https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=ijkm1234
POM_DEVELOPER_NAME=XRVLC contributors
POM_DEVELOPER_URL=https://github.com/ijkm1234

signAllPublications=false
android.nonTransitiveRClass=false
android.nonFinalResIds=false
